<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="114995" started-at="2017-12-20T19:11:45Z" finished-at="2017-12-20T19:13:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="114995" started-at="2017-12-20T19:11:45Z" finished-at="2017-12-20T19:13:40Z">
      <class name="testCases.TC001_Join_Free">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="beforeSuite" is-config="true" duration-ms="424" started-at="2017-12-21T00:41:45Z" finished-at="2017-12-21T00:41:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-12-21T00:41:45Z" finished-at="2017-12-21T00:41:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="setData" is-config="true" duration-ms="0" started-at="2017-12-21T00:41:45Z" finished-at="2017-12-21T00:41:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="beforeMethod" is-config="true" duration-ms="26486" started-at="2017-12-21T00:41:47Z" finished-at="2017-12-21T00:42:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="join_free(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="join_free" duration-ms="32739" started-at="2017-12-21T00:42:13Z" data-provider="fetchData" finished-at="2017-12-21T00:42:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testcashkaro123@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[testcash123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
	at utilities.Reporter.reportStep(Reporter.java:34)
	at utilities.Reporter.reportStep(Reporter.java:44)
	at driverMethods.SeleniumMethods.verifyTitle(SeleniumMethods.java:201)
	at pages.HomePage.<init>(HomePage.java:20)
	at pages.SignUpPage.clickJoinButton(SignUpPage.java:56)
	at testCases.TC001_Join_Free.join_free(TC001_Join_Free.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- join_free -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="afterMethod" is-config="true" duration-ms="6526" started-at="2017-12-21T00:42:47Z" finished-at="2017-12-21T00:42:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="beforeMethod" is-config="true" duration-ms="11803" started-at="2017-12-21T00:42:53Z" finished-at="2017-12-21T00:43:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="join_free(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="join_free" duration-ms="34276" started-at="2017-12-21T00:43:05Z" data-provider="fetchData" finished-at="2017-12-21T00:43:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[blah]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[blahblah1234@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[testcash123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
	at utilities.Reporter.reportStep(Reporter.java:34)
	at utilities.Reporter.reportStep(Reporter.java:44)
	at driverMethods.SeleniumMethods.type(SeleniumMethods.java:106)
	at pages.SignUpPage.enterPassword(SignUpPage.java:48)
	at testCases.TC001_Join_Free.join_free(TC001_Join_Free.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- join_free -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="afterMethod" is-config="true" duration-ms="899" started-at="2017-12-21T00:43:39Z" finished-at="2017-12-21T00:43:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-12-21T00:43:40Z" finished-at="2017-12-21T00:43:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testCases.TC001_Join_Free@1c6f14e]" name="afterSuite" is-config="true" duration-ms="1530" started-at="2017-12-21T00:43:41Z" finished-at="2017-12-21T00:43:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testCases.TC001_Join_Free -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
